### ISSUE TITLE
UI Docs: Issue in example textarea-demo

### ISSUE THREAD

**Issue by autherity** [medusajs/ui#93] opened 2023-09-30 22:20 UTC
the Textarea component imported from `@medusajs/ui` has no styling as mentioned in the docs, instead it is showing the default textarea of html
![image](https://github.com/medusajs/ui/assets/44040669/9435b95e-3dc1-4dfa-b0b4-ea6887ca9177)

**Comment by kasperkristensen** [comment] 2023-10-04 09:23
Hi @auvium, could you please provide some more info on the issue. 

Is this from a Admin widget/page your are building or are you using the UI library for a project outside of Medusa? 

From the looks off it some styles are applied, as the border-radius is not the default textarea styles, and also the placeholder text color seems to be applied correctly. So I am wondering if you have added styles to the `className` of the component that is causing the background color to be overwritten.

**Comment by kasperkristensen** [comment] 2023-10-12 13:43
I am closing this as I can't replicate it, if you can share a reproducible example or have other information please feel free re-open it.

**Closed as completed by kasperkristensen** 2023-10-12 13:43 UTC
